#!/usr/bin/env python3
"""Bundle web/translator/*.js (ES modules) into one classic script.

  tools/bundle_translator.py [-o build-web/translator.bundle.js]

The result defines `globalThis.R3T = { translate, translateSingles }` and
works in pages, workers and Emscripten --pre-js. Each module keeps its own
scope; `import {a} from './x.js'` / `export ...` are rewritten (the sources
use a strict, regex-friendly subset of module syntax).
"""
import argparse, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'web', 'translator')
ENTRY = 'translate.js'

IMPORT = re.compile(r"^import\s+(?:\{([^}]*)\}\s+from\s+)?'\./([\w.]+)';?\s*$", re.M)
EXPORT_DECL = re.compile(r"^export\s+(function|class|const|let|var)\s+(\w+)", re.M)
EXPORT_LIST = re.compile(r"^export\s+\{([^}]*)\};?\s*$", re.M)

def modname(f): return '__m_' + f.replace('.js', '').replace('.', '_')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--output', default=os.path.join(ROOT, 'build-web', 'translator.bundle.js'))
    args = ap.parse_args()
    order, seen = [], set()
    def visit(f):
        if f in seen: return
        seen.add(f)
        text = open(os.path.join(SRC, f), encoding='utf-8').read()
        for m in IMPORT.finditer(text): visit(m.group(2))
        order.append(f)
    visit(ENTRY)
    out = [';// generated by tools/bundle_translator.py -- do not edit', ';(function (root) {', "'use strict';"]
    for f in order:
        text = open(os.path.join(SRC, f), encoding='utf-8').read()
        exports = [m.group(2) for m in EXPORT_DECL.finditer(text)]
        for m in EXPORT_LIST.finditer(text):
            exports += [x.strip() for x in m.group(1).split(',') if x.strip()]
        def imp(m):
            names, dep = m.group(1), m.group(2)
            return ('const {%s} = %s;' % (names, modname(dep))) if names else ''
        body = IMPORT.sub(imp, text)
        body = EXPORT_LIST.sub('', body)
        body = EXPORT_DECL.sub(lambda m: m.group(1) + ' ' + m.group(2), body)
        if re.search(r'^\s*(import|export)\s', body, re.M):
            sys.exit('%s: unsupported import/export syntax' % f)
        out.append('const %s = (() => {' % modname(f))
        out.append(body)
        out.append('return { %s };' % ', '.join(exports))
        out.append('})();')
    out.append('root.R3T = { translate: %s.translate, translateSingles: %s.translateSingles };' % (modname(ENTRY), modname(ENTRY)))
    out.append('})(typeof globalThis !== "undefined" ? globalThis : self);')
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    open(args.output, 'w', encoding='utf-8').write('\n'.join(out) + '\n')

main()
